routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home.index');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/contact', 'HomeController@contactUs')->name('contact_us');
Route::get('/about', 'HomeController@aboutus')->name('about_us');


/********************  academic program **************************/
Route::group(['prefix' => 'academic-program'], function () {


Route::get('/', 'HomeController@academicProgram')->name('academic_program');
Route::get('/summer-camp-sat', 'HomeController@summerCampSat')->name('academic_program.summer_camp_sat');
Route::get('/summer-camp-real-core', 'HomeController@summerCampRealCore')->name('academic_program.summer_camp_realcore');
Route::get('/writer-camp-sat', 'HomeController@writerCampSat')->name('academic_program.writer_camp_sat');
Route::get('/writer-camp-real-core', 'HomeController@writerCampRealcore')->name('academic_program.writer_camp_realcore');
Route::get('/ap-sat-subject-tests', 'HomeController@apSatSubjectTests')->name('academic_program.ap_sat_subject_tests');
	});

/********************  consulting program **************************/
Route::group(['prefix' => 'news'], function () {

Route::get('/', 'HomeController@news')->name('news');


	});


/********************  news **************************/
Route::group(['prefix' => 'consulting-program'], function () {


Route::get('/', 'HomeController@consultingProgram')->name('consulting_program');

 Route::get('/application-consulting-real-service', 'HomeController@applicationConsultingRealService')->name('consulting_program.application_consulting_real_service');
 Route::get('/application-consulting-prep-service', 'HomeController@applicationConsultingPrepService')->name('consulting_program.application_consulting_prep_service');
Route::get('/general-consulting', 'HomeController@generalConsulting')->name('consulting_program.general_consulting');
Route::get('/financial-aid-consulting', 'HomeController@financialAidConsulting')->name('consulting_program.financial_aid_consulting');

	});




Route::group(['as'=>'admin.','prefix' => 'admin','namespace'=>'Admin','middleware'=>['auth','admin']], function () {
		Route::get('dashboard', 'DashboardController@index')->name('dashboard');
		/************************* Users  ****************************************/
		Route::get('users-list', 'DashboardController@usersList')->name('users_list');
		Route::get('users/add', 'DashboardController@addNewUser')->name('add_user');
		Route::post('users/add', 'DashboardController@addNewUserPost')->name('add_user_post');
		/************************* Mock test *************************************/
		Route::get('assign-mocktest', 'DashboardController@assignMocktests')->name('assign_mocktest');
		Route::get('mocktest-list', 'DashboardController@mocktestList')->name('mocktest_list');
		Route::get('mocktest/review', 'DashboardController@MocktestReviews')->name('test_review');

		Route::post('mocktest-management', 'DashboardController@assignMocktestPost')->name('mocktest_management');
		/******************** Quiz management **********************************/
		Route::get('daily-quiz', 'DashboardController@dailyQuiz')->name('daily_quiz');
		Route::get('quiz-list', 'DashboardController@quizList')->name('quiz_list');
		Route::get('quiz-review', 'DashboardController@quizReview')->name('quiz_review');
		Route::post('assign-quiz', 'DashboardController@assignDailyQuiz')->name('assign_quiz');

		/************************ Course Action ***********************************/
		Route::get('course-material/list', 'DashboardController@courseMaterialList')->name('course_list');
		Route::get('course-material/add', 'DashboardController@addCourseMaterial')->name('add_course');
		Route::post('course-material/add', 'DashboardController@addCourseMaterialPost')->name('add_course_post');
		Route::get('course-material/delete/{id}', 'DashboardController@deleteCourse')->name('delete_course');
		/************************ Announcement actions ****************************/
		Route::get('announcement/list', 'DashboardController@announcementsListing')->name('announcement_list');
		Route::get('announcement/list/{id}', 'DashboardController@announcementsView')->name('announcement_view');
		Route::get('announcement/add', 'DashboardController@addAnnouncement')->name('add_announcement');
		Route::post('announcement/add', 'DashboardController@addAnnouncementPost')->name('add_announcement_post');
		Route::get('announcement/delete/{id}', 'DashboardController@deleteAnnouncement')->name('delete_announcement');
		Route::get('announcement/edit', 'DashboardController@announcementsEdit')->name('edit_announcement');
		Route::post('announcement/edit/{id}', 'DashboardController@addAnnouncementEditPost')->name('update_announcement');
		/********************************** Assign Lecture ***********************/
		Route::get('assign-lecture', 'DashboardController@assignLectures')->name('assign_lecture');
		
		Route::post('lecture-management', 'DashboardController@assignLecturesPost')->name('lecture_management');



});
Route::group(['as'=>'user.','prefix' => 'user','namespace'=>'User','middleware'=>['auth','user']], function () {
		Route::get('dashboard', 'DashboardController@index')->name('dashboard');
		Route::get('lectures', 'DashboardController@myLectures')->name('my_lectures');
		Route::get('view-lecture', 'DashboardController@ViewLecture')->name('view_lectures');

		Route::get('mock-test', 'DashboardController@mockTest')->name('mock_test');
		Route::get('mock-test-start', 'DashboardController@getStartTest')->name('start_mock_test');
		Route::get('mock-test/start', 'DashboardController@getLoadTest')->name('load_mock_test');
		Route::post('answer-check', 'DashboardController@answerCheck')->name('answer_check');
		Route::get('break', 'DashboardController@Testbreak')->name('test_break');
		Route::get('test-result', 'DashboardController@testResult')->name('test_result');

		Route::get('quiz', 'DashboardController@userDailyQuiz')->name('quiz');
		Route::get('quiz/start', 'DashboardController@startDailyQuiz')->name('start_quiz');
		Route::get('quiz/load-omr', 'DashboardController@loadQuizOmr')->name('load_quiz_omr');
		Route::post('quiz-submit', 'DashboardController@submitQuizAnswers')->name('quiz_answer_check');
		Route::get('quiz-result', 'DashboardController@quizResult')->name('quiz_result');
		Route::get('quiz-review', 'DashboardController@quizReview')->name('quiz_review');

		Route::get('mock-test/review', 'DashboardController@reviewTestResult')->name('test_review');
		Route::get('all-mock-test/review', 'DashboardController@allMocktestReviews')->name('all_test_review');
		Route::get('course-material', 'DashboardController@allCourseMaterials')->name('course_material');

		Route::get('course-material-pdf','DashboardController@downloadCourseMaterial')->name('download_course_material');
		Route::get('announcements', 'DashboardController@userAnnoucements')->name('announcements');


});

resources/views/admin/dashboard.blade.php
@extends('layouts.admin-app')
@section('content')
<div id="content" class="main-content">
 	<div class="container">
     <div class="page-header">
         <div class="page-title">
             <h3>Dashboard</h3>
         </div>
     </div>
     @if($errors->all())
                  @foreach ($errors->all() as $index=>$error)
                   <div class="alert alert-danger">{{$error}}
                    </div>
                  @endforeach
                @endif
                @if(session('error'))
                  <div class="error alert alert-danger alert-dismissable">
                      <a href="#"  class="close" data-dismiss="alert"
                         aria-label="close">&times;</a>
                      <strong>Error : </strong> {!! session('error') !!}
                  </div>
                @endif
                @if(session('success'))
                  <div class="error alert alert-success alert-dismissable">
                      <a href="#" class="close" data-dismiss="alert"
                         aria-label="close">&times;</a>
                      {!! session('success') !!}
                  </div>
                @endif
     <div class="row layout-spacing ">
        <div class="col-xl-3 mb-xl-0 col-lg-6 mb-4 col-md-6 col-sm-6">
            <div class="widget-content-area  data-widgets br-4">
                <a href="{{route('admin.assign_lecture')}}" class="widget  t-sales-widget">
                    <div class="media">
                        <div class="icon ml-2">
                         <i class="flaticon-line-chart"></i>
                        </div>
                        <div class="media-body text-right">
                         <p class="widget-text mb-0">Lectures</p>
                        </div>
                    </div>
                </a>
            </div>
        </div>

         <div class="col-xl-3 mb-xl-0 col-lg-6 mb-4 col-md-6 col-sm-6">
            <div class="widget-content-area  data-widgets br-4">
               <a href="{{route('admin.quiz_list')}}" class="widget  t-order-widget">
                  <div class="media">
                     <div class="icon ml-2">
                        <i class="flaticon-elements"></i>
                     </div>
                     <div class="media-body text-right">
                        <p class="widget-text mb-0">Daily Quiz</p>
                     </div>
                  </div>
               </a>
            </div>
         </div>

         <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6 mb-sm-0 mb-4">
            <div class="widget-content-area  data-widgets br-4">
              <a href="{{route('admin.mocktest_list')}}" class="widget  t-customer-widget">
                  <div class="media">
                      <div class="icon ml-2">
                          <i class="flaticon-3d-cube"></i>
                      </div>
                      <div class="media-body text-right">
                          <p class="widget-text mb-0">Mock Test</p>
                         
                      </div>
                  </div>
                
              </a>
            </div>
         </div>

         <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
             
             <div class="widget-content-area  data-widgets br-4">
                 <a href="{{route('admin.course_list')}}" class="widget  t-income-widget">
                     <div class="media">
                         <div class="icon ml-2">
                             <i class="flaticon-copy-line"></i>
                         </div>
                         <div class="media-body text-right">
                             <p class="widget-text mb-0">Course Material</p>
                           
                         </div>
                     </div>
                    
                 </a>
             </div>
         </div>

     </div>
     <div class="row">
                    
        <div class="col-xl-8 col-lg-12 col-md-12 col-sm-12 layout-spacing">
            <div class="widget-content widget-content-area h-100 br-4 p-0">
                <div class="total-page-views">

                    <div class="t-page-views-header">
                        <div class="row">
                            <div class="col-md-6 col-6">
                                <h6>Total Page Views</h6>
                            </div>
                            <div class="col-md-6 col-6">
                                <ul class="nav justify-content-sm-end justify-content-center total-page-views-tab nav-pills" id="pills-tab" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="total-page-views-monthly-tab" data-toggle="pill" href="#total-page-views-monthly" role="tab" aria-controls="total-page-views-monthly" aria-selected="true">Monthly</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="total-page-views-yearly-tab" data-toggle="pill" href="#total-page-views-yearly" role="tab" aria-controls="total-page-views-yearly" aria-selected="false">Yearly</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="t-page-views-body">
                        <div class="tab-content" id="pills-tabContent">
                            <div class="tab-pane fade show active" id="total-page-views-monthly" role="tabpanel" aria-labelledby="total-page-views-monthly-tab">
                                <div class="d-flex">
                                    <div class="d-m-rate align-self-center mr-1 data-marker"></div>
                                    <span class="rate">1,10,000</span>
                                </div>
                                <div id="page-views-monthly" class="mt-4"></div>
                            </div>
                            <div class="tab-pane fade" id="total-page-views-yearly" role="tabpanel" aria-labelledby="total-page-views-yearly-tab">
                                <div class="d-flex">
                                    <div class="d-m-rate align-self-center mr-1 data-marker"></div>
                                    <span class="rate">2,70,040</span>
                                </div>
                                <div id="page-views-yearly" class="mt-4"></div>
                            </div>
                        </div>
                    </div>

                </div>                            
            </div>
        </div>

        <div class="col-xl-4 col-lg-12 col-md-12 col-sm-12 layout-spacing">
            <div class="row">

                <div class="col-md-12 mb-4">
                    <div class="widget-content-area p-0 br-4">
                        <div class="widget-content widget-content-area h-100 br-4 p-0 text-center">
                            <div class="row">
                                <div class="col-md-6 col-sm-6 col-12 pr-sm-0">
                                    <div class="date br-4">
                                        <div id="month"></div>
                                        <div id="day"></div>
                                        <div id="week"></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-12 pl-0">
                                    <div class="time">
                                        <p id="hour" class="mb-0"></p>
                                        <p id="minut" class="mb-0"></p>
                                        <p id="date" class="mb-0"></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>                                
                </div>

                <div class="col-md-12">
                    <div class="widget-content widget-content-area h-100 br-4 p-0">
                        <div class="reviews">
                            <div class="reviews-header">
                                <div class="row">
                                    <div class="col-md-12">
                                        <h6>Reviews</h6>
                                    </div>
                                </div>
                            </div>

                            <div class="reviews-body text-center">
                                <div class="row">
                                    <div class="col-md-6 col-6">                                                    
                                        <p class="r-positive-txt">Positive</p>
                                        <img alt="emoji" class="icon-positive mt-2" src="{{ asset('admin/assets/img/simple-smile.png') }}">
                                        <p class="r-positive-percentage mb-0 mt-4">78%</p>
                                    </div>
                                    <div class="col-md-6 col-6">                                                    
                                        <p class="r-negative-txt">Negative</p>
                                        <img alt="emoji" class="icon-positive mt-2" src="{{ asset('admin/assets/img/simple-sad-smile.png') }}">
                                        <p class="r-negative-percentage mb-0 mt-4">22%</p>
                                    </div>
                                    <div class="col-md-12 mt-4 mb-2">
                                        <button class="btn btn-primary btn-rounded">View Details</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>                                
                </div>

            </div>
        </div>

    </div>

     
 	</div>
</div>

@endsection('content')

resources/views/admin/left-sidebar.blade.php
<div class="sidebar-wrapper sidebar-theme">
  <div id="dismiss" class="d-lg-none"><i class="flaticon-cancel-12"></i></div>
  <nav id="sidebar">
    <ul class="navbar-nav theme-brand flex-row  d-none d-lg-flex mt-4">
      <li class="nav-item">
        <a href="index.html" >
            <img src="{{ asset('home/images/logo/Logo-RP-KR-03.png') }}" 
            style="padding: 15px 30px 0px 30px;" class="img-fluid" alt="logo">
        </a>
      </li>
    </ul>


      <ul class="list-unstyled menu-categories" id="accordionExample">
          <li class="menu">
              <a href="{{route('admin.dashboard')}}" class="dropdown-toggle">
                  <div class="">
                      <i class="flaticon-computer-6 ml-3"></i>
                      <span>Dashboard</span>
                  </div>

                  <div>
                      <span class="badge badge-pill badge-secondary mr-2">6</span>
                  </div>
              </a>
             
          </li>
          <li class="menu">
              <a href="{{route('admin.assign_lecture')}}" class="dropdown-toggle">
                  <div class="">
                      <i class="flaticon-line-chart"></i>
                      <span>Lecture</span>
                  </div>
                  <!-- <div>
                      <i class="flaticon-right-arrow"></i>
                  </div> -->
              </a>
              
          </li>
          <li class="menu">
              <a href="#Users" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                  <div class="">
                      <i class="flaticon-users"></i>
                      <span>Users</span>
                  </div>
                  <div>
                      <i class="flaticon-right-arrow"></i>
                  </div>
              </a>
              <ul class="collapse submenu list-unstyled" id="Users" data-parent="#accordionExample">
                <li>
                  <a href="{{route('admin.users_list')}}"> Users List </a>
                </li>
                <li>
                  <a href="{{route('admin.add_user')}}">Add New User</a>
                </li>
            </ul>
            
          </li>
          <li class="menu">
              <a href="#quiz_list" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                  <div class="">
                      <i class="flaticon-elements"></i>
                      <span>Daily Quiz</span>
                  </div>
                  <div>
                      <i class="flaticon-right-arrow"></i>
                  </div>
              </a>
              <ul class="collapse submenu list-unstyled" id="quiz_list" data-parent="#accordionExample">
                <li>
                  <a href="{{route('admin.quiz_list')}}"> Users Assigned List </a>
                </li>
                <li>
                  <a href="{{route('admin.daily_quiz')}}">Assign Quizzes</a>
                </li>
            </ul>
            
          </li>

          <li class="menu">
              <a href="#moacktest" class="dropdown-toggle" data-toggle="collapse" aria-expanded="false" >
                  <div class="">
                      <i class="flaticon-3d-cube"></i>
                      <span>Mock Test</span>
                  </div>
                  <div>
                      <i class="flaticon-right-arrow"></i>
                  </div>
              </a>
              <ul class="collapse submenu list-unstyled" id="moacktest" data-parent="#accordionExample">
                <li>
                  <a href="{{route('admin.mocktest_list')}}"> Users Assigned List </a>
                </li>
                <li>
                  <a href="{{route('admin.assign_mocktest')}}">Assign Mock Test</a>
                </li>
            </ul>
          </li>

          <li class="menu">
            <a href="#course_materials" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
              <div class="">
                  <i class="flaticon-copy-line"></i>
                  <span>Course Material</span>
              </div>
              <div>
                  <i class="flaticon-right-arrow"></i>
              </div>
            </a>
            <ul class="collapse submenu list-unstyled" id="course_materials" data-parent="#accordionExample">
              <li>
                <a href="{{route('admin.course_list')}}"> List </a>
              </li>
              <li>
                <a href="{{route('admin.add_course')}}"> Add New Course</a>
              </li>
            </ul>
          </li>

          <li class="menu">
              <a href="#Announcements" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                  <div class="">
                      <i class="flaticon-layers"></i>
                      <span>Announcements</span>
                  </div>
                  <div>
                      <i class="flaticon-right-arrow"></i>
                  </div>
              </a>
              <ul class="collapse submenu list-unstyled" id="Announcements" data-parent="#accordionExample">
              <li>
                <a href="{{route('admin.announcement_list')}}"> List </a>
              </li>
              <li>
                <a href="{{route('admin.add_announcement')}}"> Add New Announcement</a>
              </li>
            </ul>
            
          </li>
          <li class="menu">
            <a class="dropdown-toggle" href="{{ route('logout') }}" 
            onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
              <div class="">
                   <i class="mr-1 flaticon-power-button"></i>
                  <span>{{ __('Logout') }}</span>
              </div>

             
            </a>
             <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
          </li>
      </ul>
  </nav>
</div>