routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home.index');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/contact', 'HomeController@contactUs')->name('contact_us');
Route::get('/about', 'HomeController@aboutus')->name('about_us');


/********************  academic program **************************/
Route::group(['prefix' => 'academic-program'], function () {


Route::get('/', 'HomeController@academicProgram')->name('academic_program');
Route::get('/summer-camp-sat', 'HomeController@summerCampSat')->name('academic_program.summer_camp_sat');
Route::get('/summer-camp-real-core', 'HomeController@summerCampRealCore')->name('academic_program.summer_camp_realcore');
Route::get('/writer-camp-sat', 'HomeController@writerCampSat')->name('academic_program.writer_camp_sat');
Route::get('/writer-camp-real-core', 'HomeController@writerCampRealcore')->name('academic_program.writer_camp_realcore');
Route::get('/ap-sat-subject-tests', 'HomeController@apSatSubjectTests')->name('academic_program.ap_sat_subject_tests');
	});

/********************  consulting program **************************/
Route::group(['prefix' => 'news'], function () {

Route::get('/', 'HomeController@news')->name('news');


	});


/********************  news **************************/
Route::group(['prefix' => 'consulting-program'], function () {


Route::get('/', 'HomeController@consultingProgram')->name('consulting_program');

 Route::get('/application-consulting-real-service', 'HomeController@applicationConsultingRealService')->name('consulting_program.application_consulting_real_service');
 Route::get('/application-consulting-prep-service', 'HomeController@applicationConsultingPrepService')->name('consulting_program.application_consulting_prep_service');
Route::get('/general-consulting', 'HomeController@generalConsulting')->name('consulting_program.general_consulting');
Route::get('/financial-aid-consulting', 'HomeController@financialAidConsulting')->name('consulting_program.financial_aid_consulting');

	});




Route::group(['as'=>'admin.','prefix' => 'admin','namespace'=>'Admin','middleware'=>['auth','admin']], function () {
		Route::get('dashboard', 'DashboardController@index')->name('dashboard');
		/************************* Users  ****************************************/
		Route::get('users-list', 'DashboardController@usersList')->name('users_list');
		Route::get('users/add', 'DashboardController@addNewUser')->name('add_user');
		Route::post('users/add', 'DashboardController@addNewUserPost')->name('add_user_post');
		/************************* Mock test *************************************/
		Route::get('assign-mocktest', 'DashboardController@assignMocktests')->name('assign_mocktest');
		Route::get('mocktest-list', 'DashboardController@mocktestList')->name('mocktest_list');
		Route::get('mocktest/review', 'DashboardController@MocktestReviews')->name('test_review');

		Route::post('mocktest-management', 'DashboardController@assignMocktestPost')->name('mocktest_management');
		/******************** Quiz management **********************************/
		Route::get('daily-quiz', 'DashboardController@dailyQuiz')->name('daily_quiz');
		Route::get('quiz-list', 'DashboardController@quizList')->name('quiz_list');
		Route::get('quiz-review', 'DashboardController@quizReview')->name('quiz_review');
		Route::post('assign-quiz', 'DashboardController@assignDailyQuiz')->name('assign_quiz');

		/************************ Course Action ***********************************/
		Route::get('course-material/list', 'DashboardController@courseMaterialList')->name('course_list');
		Route::get('course-material/add', 'DashboardController@addCourseMaterial')->name('add_course');
		Route::post('course-material/add', 'DashboardController@addCourseMaterialPost')->name('add_course_post');
		Route::get('course-material/delete/{id}', 'DashboardController@deleteCourse')->name('delete_course');
		/************************ Announcement actions ****************************/
		Route::get('announcement/list', 'DashboardController@announcementsListing')->name('announcement_list');
		Route::get('announcement/list/{id}', 'DashboardController@announcementsView')->name('announcement_view');
		Route::get('announcement/add', 'DashboardController@addAnnouncement')->name('add_announcement');
		Route::post('announcement/add', 'DashboardController@addAnnouncementPost')->name('add_announcement_post');
		Route::get('announcement/delete/{id}', 'DashboardController@deleteAnnouncement')->name('delete_announcement');
		Route::get('announcement/edit', 'DashboardController@announcementsEdit')->name('edit_announcement');
		Route::post('announcement/edit/{id}', 'DashboardController@addAnnouncementEditPost')->name('update_announcement');
		/********************************** Assign Lecture ***********************/
		Route::get('assign-lecture', 'DashboardController@assignLectures')->name('assign_lecture');
		
		Route::post('lecture-management', 'DashboardController@assignLecturesPost')->name('lecture_management');



});
Route::group(['as'=>'user.','prefix' => 'user','namespace'=>'User','middleware'=>['auth','user']], function () {
		Route::get('dashboard', 'DashboardController@index')->name('dashboard');
		Route::get('lectures', 'DashboardController@myLectures')->name('my_lectures');
		Route::get('view-lecture', 'DashboardController@ViewLecture')->name('view_lectures');

		Route::get('mock-test', 'DashboardController@mockTest')->name('mock_test');
		Route::get('mock-test-start', 'DashboardController@getStartTest')->name('start_mock_test');
		Route::get('mock-test/start', 'DashboardController@getLoadTest')->name('load_mock_test');
		Route::post('answer-check', 'DashboardController@answerCheck')->name('answer_check');
		Route::get('break', 'DashboardController@Testbreak')->name('test_break');
		Route::get('test-result', 'DashboardController@testResult')->name('test_result');

		Route::get('quiz', 'DashboardController@userDailyQuiz')->name('quiz');
		Route::get('quiz/start', 'DashboardController@startDailyQuiz')->name('start_quiz');
		Route::get('quiz/load-omr', 'DashboardController@loadQuizOmr')->name('load_quiz_omr');
		Route::post('quiz-submit', 'DashboardController@submitQuizAnswers')->name('quiz_answer_check');
		Route::get('quiz-result', 'DashboardController@quizResult')->name('quiz_result');
		Route::get('quiz-review', 'DashboardController@quizReview')->name('quiz_review');

		Route::get('mock-test/review', 'DashboardController@reviewTestResult')->name('test_review');
		Route::get('all-mock-test/review', 'DashboardController@allMocktestReviews')->name('all_test_review');
		Route::get('course-material', 'DashboardController@allCourseMaterials')->name('course_material');

		Route::get('course-material-pdf','DashboardController@downloadCourseMaterial')->name('download_course_material');
		Route::get('announcements', 'DashboardController@userAnnoucements')->name('announcements');


});

resources/views/admin/announcements/add.blade.php
@extends('layouts.admin-app')
@section('content')
<div id="content" class="main-content">
   <div class="container">
     <div class="page-header">
       <div class="page-title">
          <h3>Announcements</h3>
       </div>
     </div>
     <div class="row layout-spacing ">
        <div class="col-lg-12 layout-spacing">
            <div class="statbox widget box box-shadow">
               <div class="widget-header">
                  <div class="row">
                     <div class="col-xl-10 col-md-10 col-sm-10 col-10">
                         <h4 class="text-center"><b>Add New Announcements</b><hr/></h4>
                     </div>
                     <div class="col-xl-2 col-md-2 col-sm-2 col-2 mt-2">
                         <a href="{{route('admin.announcement_list')}}" class = 'button-lnk nav-link formButton transparentformButton'>Back </a>
                     </div>
                  </div>
               </div>
               <div class="widget-content widget-content-area">
                @if($errors->all())
                  @foreach ($errors->all() as $index=>$error)
                   <div class="error alert alert-danger alert-dismissable">
                      <a href="#"  class="close" data-dismiss="alert"
                         aria-label="close">&times;</a>
                      <strong>Error : </strong> {{$error}}
                  </div>
                  @endforeach
                @endif
                @if(session('error'))
                  <div class="error alert alert-danger alert-dismissable">
                      <a href="#"  class="close" data-dismiss="alert"
                         aria-label="close">&times;</a>
                      <strong>Error : </strong> {!! session('error') !!}
                  </div>
                @endif
                @if(session('success'))
                  <div class="error alert alert-success alert-dismissable">
                      <a href="#" class="close" data-dismiss="alert"
                         aria-label="close">&times;</a>
                      {!! session('success') !!}
                  </div>
                @endif
                   <form action="{{route('admin.add_announcement_post')}}" enctype="multipart/form-data" method="post">
                     @csrf
                     <div class="form-group mb-4 col-md-4">
                        <label for="title">Announcement title</label>
                         <input type="text" name="title" class="form-control" id="title">
                          @error('title')
                          <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('title') }}</strong>
                          </span>
                        @enderror
                     </div>
                     <div class="form-group mb-4 col-md-4">
                        <label for="Content">Content</label>
                         <textarea name="content" class="form-control"></textarea>
                          @error('content')
                          <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('content') }}</strong>
                          </span>
                        @enderror
                     </div>
                     <input type="submit" name="course" value="Submit" class="mt-4 mb-4 btn btn-button-7">
                     
                  </form>
               </div>
            </div>
        </div>
     </div>
   </div>
</div>
@endsection('content')

resources/views/admin/announcements/edit.blade.php
@extends('layouts.admin-app')
@section('content')
<div id="content" class="main-content">
   <div class="container">
     <div class="page-header">
       <div class="page-title">
          <h3>Announcements</h3>
       </div>
     </div>
     <div class="row layout-spacing ">
        <div class="col-lg-12 layout-spacing">
            <div class="statbox widget box box-shadow">
               <div class="widget-header">
                  <div class="row">
                     <div class="col-xl-10 col-md-10 col-sm-10 col-10">
                         <h4 class="text-center"><b>Update Announcements</b><hr/></h4>
                     </div>
                     <div class="col-xl-2 col-md-2 col-sm-2 col-2 mt-2">
                         <a href="{{route('admin.announcement_list')}}" class = 'button-lnk nav-link formButton transparentformButton'>Back </a>
                     </div>
                  </div>
               </div>
               <div class="widget-content widget-content-area">
                @if($errors->all())
                  @foreach ($errors->all() as $index=>$error)
                   <div class="error alert alert-danger alert-dismissable">
                      <a href="#"  class="close" data-dismiss="alert"
                         aria-label="close">&times;</a>
                      <strong>Error : </strong> {{$error}}
                  </div>
                  @endforeach
                @endif
                @if(session('error'))
                  <div class="error alert alert-danger alert-dismissable">
                      <a href="#"  class="close" data-dismiss="alert"
                         aria-label="close">&times;</a>
                      <strong>Error : </strong> {!! session('error') !!}
                  </div>
                @endif
                @if(session('success'))
                  <div class="error alert alert-success alert-dismissable">
                      <a href="#" class="close" data-dismiss="alert"
                         aria-label="close">&times;</a>
                      {!! session('success') !!}
                  </div>
                @endif
                   <form action="{{route('admin.update_announcement',$Selectedboard->id)}}" enctype="multipart/form-data" method="post">
                     @csrf
                     <div class="form-group mb-4 col-md-5">
                        <label for="title">Announcement title</label>
                         <input type="text" name="title" value="{{$Selectedboard->title}}" class="form-control" id="title">
                          @error('title')
                          <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('title') }}</strong>
                          </span>
                        @enderror
                     </div>
                     <div class="form-group mb-4 col-md-5">
                        <label for="Content">Content</label>
                         <textarea name="content" class="form-control" rows="10">{{$Selectedboard->content}}</textarea>
                          @error('content')
                          <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('content') }}</strong>
                          </span>
                        @enderror
                     </div>
                     <input type="submit" name="course" value="Update" class="mt-4 mb-4 btn btn-button-7">
                     
                  </form>
               </div>
            </div>
        </div>
     </div>
   </div>
</div>
@endsection('content')

resources/views/admin/announcements/listing.blade.php
@extends('layouts.admin-app')
@section('content')
<div id="content" class="main-content">
   <div class="container">
     <div class="page-header">
         <div class="page-title">
             <h3>Announcements</h3>
         </div>
     </div>

     <div class="row layout-spacing ">
        <div class="col-lg-12 layout-spacing">
            <div class="statbox widget box box-shadow">
               <div class="widget-header">
                  <div class="row">
                     <div class="col-xl-9 col-md-9 col-sm-9 col-9">
                         <h4 class="text-center"><b>Announcements Listing</b><hr/></h4>
                     </div>
                     <div class="col-xl-3 col-md-3 col-sm-3 col-3 mt-3">
                         <a href="{{route('admin.add_announcement')}}" class = 'button-lnk nav-link formButton transparentformButton'>Add Announcements</a>
                     </div>
                  </div>
               </div>
               <div class="widget-content widget-content-area">
                @if($errors->all())
                  @foreach ($errors->all() as $index=>$error)
                   <div class="alert alert-danger">{{$error}}
                    </div>
                  @endforeach
                @endif
                @if(session('error'))
                  <div class="error alert alert-danger alert-dismissable">
                      <a href="#"  class="close" data-dismiss="alert"
                         aria-label="close">&times;</a>
                      <strong>Error : </strong> {!! session('error') !!}
                  </div>
                @endif
                @if(session('success'))
                  <div class="error alert alert-success alert-dismissable">
                      <a href="#" class="close" data-dismiss="alert"
                         aria-label="close">&times;</a>
                      {!! session('success') !!}
                  </div>
                @endif
                  <div class="table-responsive">
                     <table class="table table-bordered table-hover table-striped mb-4">
                        <thead>
                           <tr>
                              <th>#</th>
                              <th>Title</th>
                              <th>Date</th>
                              <th class="text-center">Action</th>
                             
                           </tr>
                        </thead>
                        <tbody>
                           @foreach($announcements as $announcement)
                           <tr>
                              <td>{{$loop->iteration}}</td>
                              <td>{{$announcement->title }}</td>
                              <td>{{ \Carbon\Carbon::parse($announcement->updated_at)->format('F jS, Y')}}</td>
                            
                              <td class="user-mobile nav-item d-flex text-center">
                                <a href="{{ route('admin.announcement_view',['id'=>$announcement->id]) }}" class = 'button-lnk nav-link formButton transparentformButton'>View </a>
                                <a href="{{ route('admin.delete_announcement',['id'=>$announcement->id]) }}" onclick="return confirm('Are you sure to want delete this?')" class = 'button-lnk nav-link formButton ml-2'><span class="icon-trash"></span> Delete</a>
                                <a href="{{ route('admin.edit_announcement',['id'=>$announcement->id]) }}" class = 'button-lnk nav-link formButton transparentformButton ml-2'>Edit </a>
                              </td>
                           </tr>
                           @endforeach
                        </tbody>
                     </table>
                     <div class="widget-content widget-content-area text-center">
                        <ul class="pagination pagination-style-13 pagination-bordered justify-content-center mb-5">
                          {!! $announcements->links() !!}
                        </ul>
                      </div>
                  </div>
               </div>
            </div>
        </div>
     </div>
   </div>
</div>
@endsection('content')

resources/views/admin/announcements/show.blade.php
@extends('layouts.admin-app')
@section('content')
<div id="content" class="main-content">
   <div class="container">
     <div class="page-header">
         <div class="page-title">
             <h3>Announcements</h3>
         </div>
     </div>

     <div class="row layout-spacing ">
        <!-- <div class="col-lg-7 layout-spacing">
            <div class="statbox widget box box-shadow">
               <div class="widget-header">
                  <div class="row">
                     <div class="col-xl-9 col-md-9 col-sm-9 col-9">
                         <h4 class="text-center"><b>Announcements Listing</b><hr/></h4>
                     </div>
                     <div class="col-xl-2 col-md-2 col-sm-2 col-2 mt-2">
                         <a href="{{route('admin.announcement_list')}}" class = 'button-lnk nav-link formButton transparentformButton'>Back </a>
                     </div>
                  </div>
               </div>
               <div class="widget-content widget-content-area">
                @if($errors->all())
                  @foreach ($errors->all() as $index=>$error)
                   <div class="alert alert-danger">{{$error}}
                    </div>
                  @endforeach
                @endif
                @if(session('error'))
                  <div class="error alert alert-danger alert-dismissable">
                      <a href="#"  class="close" data-dismiss="alert"
                         aria-label="close">&times;</a>
                      <strong>Error : </strong> {!! session('error') !!}
                  </div>
                @endif
                @if(session('success'))
                  <div class="error alert alert-success alert-dismissable">
                      <a href="#" class="close" data-dismiss="alert"
                         aria-label="close">&times;</a>
                      {!! session('success') !!}
                  </div>
                @endif
                  <div class="table-responsive">
                     <table class="table table-bordered table-hover table-striped mb-4">
                        <thead>
                           <tr>
                              <th>#</th>
                              <th>Title</th>
                              <th>Date</th>
                              <th class="text-center">Action</th>
                             
                           </tr>
                        </thead>
                        <tbody>
                           @foreach($announcements as $announcement)
                           <tr>
                              <td>{{$loop->iteration}}</td>
                              <td>{{$announcement->title }}</td>
                              <td>{{ \Carbon\Carbon::parse($announcement->updated_at)->format('F jS, Y')}}</td>
                            
                              <td class="user-mobile nav-item d-flex text-center">
                                <a href="{{ route('admin.announcement_view',['id'=>$announcement->id]) }}"  class = 'button-lnk nav-link formButton transparentformButton'>View </a>
                                <a href="{{ route('admin.delete_announcement',['id'=>$announcement->id]) }}" onclick="return confirm('Are you sure to want delete this?')" class = 'button-lnk nav-link formButton ml-2'><span class="icon-trash"></span> Delete</a>
                              </td>
                           </tr>
                           @endforeach
                        </tbody>
                     </table>
                     <div class="widget-content widget-content-area text-center">
                        <ul class="pagination pagination-style-13 pagination-bordered justify-content-center mb-5">
                          {!! $announcements->links() !!}
                        </ul>
                      </div>
                  </div>
               </div>
            </div>
        </div> -->
        @if($Selectedboard !='')
          <div class="col-lg-12 col-md-12 layout-spacing">
            <div class="widget portlet-widget">
              <div class="widget-content widget-content-area">
                <div class="portlet portlet-warning">
                  <div class="portlet-title portlet-warning d-flex justify-content-between">
                    <div class="caption  align-self-center">
                      <span class="caption-subject text-uppercase white ml-1"> Announcement View</span>
                    </div>
                    <div class="actions  align-self-center">
                     <!--  <a href="{{ route('admin.edit_announcement',['id'=>$Selectedboard->id]) }}" class="btn btn-red btn-circle">
                        <i class="flaticon-edit-7"></i>
                      </a> -->
                      <a href="{{route('admin.announcement_list')}}" class = 'button-lnk nav-link formButton transparentformButton'>Back </a>
                      
                    </div>
                  </div>
                  <div class="portlet-body portlet-common-body">
                      <h4 class="text-center">{!! nl2Br($Selectedboard->title) !!}</h4>
                      <p class="mb-4 ml-5">{!! nl2Br($Selectedboard->content) !!}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        @endif
     </div>
   </div>
</div>
@endsection('content')