routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home.index');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/contact', 'HomeController@contactUs')->name('contact_us');
Route::get('/about', 'HomeController@aboutus')->name('about_us');


/********************  academic program **************************/
Route::group(['prefix' => 'academic-program'], function () {


Route::get('/', 'HomeController@academicProgram')->name('academic_program');
Route::get('/summer-camp-sat', 'HomeController@summerCampSat')->name('academic_program.summer_camp_sat');
Route::get('/summer-camp-real-core', 'HomeController@summerCampRealCore')->name('academic_program.summer_camp_realcore');
Route::get('/writer-camp-sat', 'HomeController@writerCampSat')->name('academic_program.writer_camp_sat');
Route::get('/writer-camp-real-core', 'HomeController@writerCampRealcore')->name('academic_program.writer_camp_realcore');
Route::get('/ap-sat-subject-tests', 'HomeController@apSatSubjectTests')->name('academic_program.ap_sat_subject_tests');
	});

/********************  consulting program **************************/
Route::group(['prefix' => 'news'], function () {

Route::get('/', 'HomeController@news')->name('news');


	});


/********************  news **************************/
Route::group(['prefix' => 'consulting-program'], function () {


Route::get('/', 'HomeController@consultingProgram')->name('consulting_program');

 Route::get('/application-consulting-real-service', 'HomeController@applicationConsultingRealService')->name('consulting_program.application_consulting_real_service');
 Route::get('/application-consulting-prep-service', 'HomeController@applicationConsultingPrepService')->name('consulting_program.application_consulting_prep_service');
Route::get('/general-consulting', 'HomeController@generalConsulting')->name('consulting_program.general_consulting');
Route::get('/financial-aid-consulting', 'HomeController@financialAidConsulting')->name('consulting_program.financial_aid_consulting');

	});




Route::group(['as'=>'admin.','prefix' => 'admin','namespace'=>'Admin','middleware'=>['auth','admin']], function () {
		Route::get('dashboard', 'DashboardController@index')->name('dashboard');
		/************************* Users  ****************************************/
		Route::get('users-list', 'DashboardController@usersList')->name('users_list');
		Route::get('users/add', 'DashboardController@addNewUser')->name('add_user');
		Route::post('users/add', 'DashboardController@addNewUserPost')->name('add_user_post');
		/************************* Mock test *************************************/
		Route::get('assign-mocktest', 'DashboardController@assignMocktests')->name('assign_mocktest');
		Route::get('mocktest-list', 'DashboardController@mocktestList')->name('mocktest_list');
		Route::get('mocktest/review', 'DashboardController@MocktestReviews')->name('test_review');

		Route::post('mocktest-management', 'DashboardController@assignMocktestPost')->name('mocktest_management');
		/******************** Quiz management **********************************/
		Route::get('daily-quiz', 'DashboardController@dailyQuiz')->name('daily_quiz');
		Route::get('quiz-list', 'DashboardController@quizList')->name('quiz_list');
		Route::get('quiz-review', 'DashboardController@quizReview')->name('quiz_review');
		Route::post('assign-quiz', 'DashboardController@assignDailyQuiz')->name('assign_quiz');

		/************************ Course Action ***********************************/
		Route::get('course-material/list', 'DashboardController@courseMaterialList')->name('course_list');
		Route::get('course-material/add', 'DashboardController@addCourseMaterial')->name('add_course');
		Route::post('course-material/add', 'DashboardController@addCourseMaterialPost')->name('add_course_post');
		Route::get('course-material/delete/{id}', 'DashboardController@deleteCourse')->name('delete_course');
		/************************ Announcement actions ****************************/
		Route::get('announcement/list', 'DashboardController@announcementsListing')->name('announcement_list');
		Route::get('announcement/list/{id}', 'DashboardController@announcementsView')->name('announcement_view');
		Route::get('announcement/add', 'DashboardController@addAnnouncement')->name('add_announcement');
		Route::post('announcement/add', 'DashboardController@addAnnouncementPost')->name('add_announcement_post');
		Route::get('announcement/delete/{id}', 'DashboardController@deleteAnnouncement')->name('delete_announcement');
		Route::get('announcement/edit', 'DashboardController@announcementsEdit')->name('edit_announcement');
		Route::post('announcement/edit/{id}', 'DashboardController@addAnnouncementEditPost')->name('update_announcement');
		/********************************** Assign Lecture ***********************/
		Route::get('assign-lecture', 'DashboardController@assignLectures')->name('assign_lecture');
		
		Route::post('lecture-management', 'DashboardController@assignLecturesPost')->name('lecture_management');



});
Route::group(['as'=>'user.','prefix' => 'user','namespace'=>'User','middleware'=>['auth','user']], function () {
		Route::get('dashboard', 'DashboardController@index')->name('dashboard');
		Route::get('lectures', 'DashboardController@myLectures')->name('my_lectures');
		Route::get('view-lecture', 'DashboardController@ViewLecture')->name('view_lectures');

		Route::get('mock-test', 'DashboardController@mockTest')->name('mock_test');
		Route::get('mock-test-start', 'DashboardController@getStartTest')->name('start_mock_test');
		Route::get('mock-test/start', 'DashboardController@getLoadTest')->name('load_mock_test');
		Route::post('answer-check', 'DashboardController@answerCheck')->name('answer_check');
		Route::get('break', 'DashboardController@Testbreak')->name('test_break');
		Route::get('test-result', 'DashboardController@testResult')->name('test_result');

		Route::get('quiz', 'DashboardController@userDailyQuiz')->name('quiz');
		Route::get('quiz/start', 'DashboardController@startDailyQuiz')->name('start_quiz');
		Route::get('quiz/load-omr', 'DashboardController@loadQuizOmr')->name('load_quiz_omr');
		Route::post('quiz-submit', 'DashboardController@submitQuizAnswers')->name('quiz_answer_check');
		Route::get('quiz-result', 'DashboardController@quizResult')->name('quiz_result');
		Route::get('quiz-review', 'DashboardController@quizReview')->name('quiz_review');

		Route::get('mock-test/review', 'DashboardController@reviewTestResult')->name('test_review');
		Route::get('all-mock-test/review', 'DashboardController@allMocktestReviews')->name('all_test_review');
		Route::get('course-material', 'DashboardController@allCourseMaterials')->name('course_material');

		Route::get('course-material-pdf','DashboardController@downloadCourseMaterial')->name('download_course_material');
		Route::get('announcements', 'DashboardController@userAnnoucements')->name('announcements');


});

app/Http/Controllers/User/DashboardController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\rawTest;
use App\student;
use App\file;
use App\Board;
use App\answerTest;
use App\scoreTest;

use App\AnswerQuiz;
use App\ScoreQuiz;

use App\conversionTable2;
use App\conversionTable1;
use Illuminate\Support\Facades\Auth;
use Response;
use DB;
use Carbon\Carbon;
use PDF;
use App\Http\Helpers\helpers;
class DashboardController extends Controller
{
      public function index()
   	{
         $user_id=Auth::user()->id;
         $student=student::where('user_id',$user_id)->first();
   		return view('user.index',compact('student'));
   	}
   	public function myLectures()
   	{
   		if(Auth::check())
      {
   			$user_id=Auth::user()->id;
   			$student=student::where('user_id',$user_id)->first();
   			//echo "<pre>";print_r($student->toArray());die;
   			return view('user.lectures',compact('student'));
   		}
   	}
   	public function ViewLecture(Request $request)
   	{
   		if(Auth::check())
         {
   			$user_id=Auth::user()->id;
   			$student=student::where('user_id',$user_id)->first();
   			//echo "<pre>";print_r($student->toArray());die;
   			$type = $request->type;
				$file =  $request->file;
   			return view('user.view-lectures',compact('student','type','file'));
   		}
   	}
   	public function mockTest(Request $request)
   	{
   		if(Auth::check())
         {
   			$user_id=Auth::user()->id;
   			$student=student::where('user_id',$user_id)->first();
   			//echo "<pre>";print_r($student->toArray());die;
   			$type = $request->type;
				$file =  $request->file;
            $scoreTests=scoreTest::where(['user_id'=>$user_id])->get();
   			return view('user.mock-tests',compact('student','type','file','scoreTests'));
   		}
   	}
     

      public function getStartTest(Request $request)
      {
         if(Auth::check())
         {
            $user_id=Auth::user()->id;
            $student=student::where('user_id',$user_id)->first();

            $type       = $request->type;
            $test_no = $request->test;
            $test_section1 = $student->section_1;
            $test_section2 = $student->section_2;
            $test_section3 = $student->section_3;
            $test_section4 = $student->section_4;
            //echo "skfjhjskdhfhs".$test_section1;die;
            if ($test_section1 == 'o')
            {
               //function_page_relocation('../test/start.php?test='.$test_no);
               //return redirect()->route('user.load_mock_test',['test'=>$test_no]);
               return view('user.start-mock-tests',compact('student','test_no'));
            }
            elseif ($test_section2 == 'o')
            {
               return redirect()->route("user.load_mock_test",['test'=>$test_no,'section'=>2]);
            }
            elseif ($test_section3 == 'o')
            {
               return redirect()->route("user.load_mock_test",['test'=>$test_no,'section'=>3]);
            }
            else
            {
               return redirect()->route("user.load_mock_test",['test'=>$test_no,'section'=>4]);
            }

           
            //echo "<pre>";print_r($student->toArray());die;
            
            
         }
      }
      public function getLoadTest(Request $request)
      {
         $user_id=Auth::user()->id;
         $student=student::where('user_id',$user_id)->first();

         $test_no = $request->test;
         $section = $request->section;
         $test_section='section_'.$section;
         //echo "<pre>";print_r($test_section);die;
         if(isset($section) && isset($test_no) && $test_no !='' && $student->$test_section !='x')
         {
            $date = date("Y-m-d");
            $rawTest=rawTest::where(['test'=>$test_no,'test_date'=>$date,'user_id'=>$user_id])->get();
            if(!isset($rawTest) || count($rawTest)<=0 )
            {
               $rawTests=new rawTest;
               $rawTests->test=$test_no;
               $rawTests->test_date=$date;
               $rawTests->user_id=$user_id;
               $rawTests->save();
            }
         }
         else
         {
            $message="<b>You do not have access to this test. !!!</b>";
            return redirect()->route('user.mock_test')->with('error',$message);
         }
         if(isset($section) && $section =='1')
         {
            
            
            if($student->section_1=='o')
            {
               $student->section_1='x';
               $student->save();
            }
            $section='1';

            return view('user.omr-section-1',compact('student','test_no','date','section'));
         }
         else if(isset($section) && $section =='2')
         {
            if($student->section_2=='o')
            {
               $student->section_2='x';
               $student->save();
            }
            $section='2';
            return view('user.omr-section-2',compact('student','test_no','date','section'));
         }
         else if(isset($section) && $section =='3')
         {
            if($student->section_3=='o')
            {
               $student->section_3='x';
               $student->save();
            }
            $section='3';
            return view('user.omr-section-3',compact('student','test_no','date','section'));
         }
         else if(isset($section) && $section =='4')
         {
            if($student->section_4=='o')
            {
               $student->section_4='x';
               $student->test=0;
               $student->save();
            }
            $section='4';
            return view('user.omr-section-4',compact('student','test_no','date','section'));
         }
         else
         {
            $message="<b>You do not have access to this mock test.</b>";
            return redirect()->route('user.mock_test')->with('error',$message);
         }
         //echo "<pre>";print_r($request->all());die;
         
      }
      public function answerCheck(Request $request)
      {
         $test = $request->test;
         $section = $request->section;
         $date = date("Y-m-d");
         $user_id=Auth::user()->id;
         if($section == '')
         {
            $student=student::where('user_id',$user_id)->first();
            $rawTest=rawTest::where(['test'=>$test,'test_date'=>$date,'user_id'=>$user_id])->get();
            if(empty($rawTest) )
            {
               $rawTests=new rawTest;
               $rawTests->test=$test;
               $rawTests->test_date=$date;
               $rawTests->user_id=$user_id;
               $rawTests->save();

            }
            return redirect()->route("user.load_mock_test",['test'=>$test,'section'=>1]);
         }
         elseif($section == '1')
         {
            $a1 = array();
            $data =  array();

            for ($i = 101; $i < 153; $i++)
            {
               if(!isset($_POST[$i]) || $_POST[$i] == '')
               {
                  $_POST[$i] = 0;
               }
               $a1[$i-100] = $_POST[$i];
               //$data[$i]=$_POST[$i];
               
            }
            
            //echo "<pre>";print_r($request->all());
            //$array = array_dot($data);
          //print_r($data );die;
           // $rawTest=rawTest::where(['test'=>$test,'test_date'=>$date,'user_id'=>$user_id])->update($data);
            $sql =   "UPDATE raw_tests SET `101` = '$a1[1]', `102` = '$a1[2]', `103` = '$a1[3]', `104` = '$a1[4]', `105` = '$a1[5]', 
                         `106` = '$a1[6]', `107` = '$a1[7]', `108` = '$a1[8]', `109` = '$a1[9]', `110` = '$a1[10]',
                         `111` = '$a1[11]', `112` = '$a1[12]', `113` = '$a1[13]', `114` = '$a1[14]', `115` = '$a1[15]',
                         `116` = '$a1[16]', `117` = '$a1[17]', `118` = '$a1[18]', `119` = '$a1[19]', `120` = '$a1[20]',
                         `121` = '$a1[21]', `122` = '$a1[22]', `123` = '$a1[23]', `124` = '$a1[24]', `125` = '$a1[25]', 
                         `126` = '$a1[26]', `127` = '$a1[27]', `128` = '$a1[28]', `129` = '$a1[29]', `130` = '$a1[30]',
                         `131` = '$a1[31]', `132` = '$a1[32]', `133` = '$a1[33]', `134` = '$a1[34]', `135` = '$a1[35]',
                         `136` = '$a1[36]', `137` = '$a1[37]', `138` = '$a1[38]', `139` = '$a1[39]', `140` = '$a1[40]',
                         `141` = '$a1[41]', `142` = '$a1[42]', `143` = '$a1[43]', `144` = '$a1[44]', `145` = '$a1[45]',
                         `146` = '$a1[46]', `147` = '$a1[47]', `148` = '$a1[48]', `149` = '$a1[49]', `150` = '$a1[50]',`151` = '$a1[41]', `152` = '$a1[52]' WHERE `user_id` = '$user_id' AND `test` = '$test' AND `test_date` = '$date'";
               DB::update($sql);
               //echo $sql;die;
               //function_page_relocation('../test/break.php?test='.$test.'&break=1&date='.$date);
               return redirect()->route("user.test_break",['test'=>$test,'section'=>1,'break'=>1,'date'=>$date]);
         }
         elseif($section == '2')
         {
            $a2 = array();
            for ($i = 201; $i < 245; $i++)
            {
               if(!isset($_POST[$i]) || $_POST[$i] == '')
               {
                  $_POST[$i] = 0;
               }
               $a2[$i-200] = $_POST[$i];
               
            }
           $sql =    "UPDATE raw_tests SET `201` = '$a2[1]', `202` = '$a2[2]', `203` = '$a2[3]', `204` = '$a2[4]', `205` = '$a2[5]', 
                         `206` = '$a2[6]', `207` = '$a2[7]', `208` = '$a2[8]', `209` = '$a2[9]', `210` = '$a2[10]',
                         `211` = '$a2[11]', `212` = '$a2[12]', `213` = '$a2[13]', `214` = '$a2[14]', `215` = '$a2[15]',
                         `216` = '$a2[16]', `217` = '$a2[17]', `218` = '$a2[18]', `219` = '$a2[19]', `220` = '$a2[20]',
                         `221` = '$a2[21]', `222` = '$a2[22]', `223` = '$a2[23]', `224` = '$a2[24]', `225` = '$a2[25]', 

resources/views/user/index.blade.php
@extends('layouts.user-app')
@section('content')
<div id="content" class="main-content">
   <div class="container">
      <div class="page-header">
         <div class="page-title">
            <h3>Dashboard</h3>
         </div>
      </div>
      <div class="row">
          @if($errors->all())
        @foreach ($errors->all() as $index=>$error)
         <div class="alert alert-danger">{{$error}}
          </div>
        @endforeach
      @endif
      @if(session('error'))
        <div class="error alert alert-danger alert-dismissable">
            <a href="#"  class="close" data-dismiss="alert"
               aria-label="close">&times;</a>
            <strong>Error : </strong> {!! session('error') !!}
        </div>
      @endif
      @if(session('success'))
        <div class="error alert alert-success alert-dismissable">
            <a href="#" class="close" data-dismiss="alert"
               aria-label="close">&times;</a>
            {!! session('success') !!}
        </div>
      @endif

      </div>
      <div class="row layout-spacing ">
         <a href="{{route('user.my_lectures')}}" class="col-xl-3 mb-xl-0 col-lg-6 mb-4 col-md-6 col-sm-6">
             <div class="widget-content-area  data-widgets br-4">
                 <div class="widget  t-sales-widget">
                     <div class="media">
                         <div class="icon ml-2">
                             <i class="flaticon-3d-cube"></i>
                         </div>
                         <div class="media-body text-right">
                             <p class="widget-text mb-0">My Lectures</p>
                             
                         </div>
                     </div>
                     <!-- <p class="widget-total-stats mt-2">94% New Sales</p> -->
                 </div>
             </div>
         </a>
         <a href="{{route('user.mock_test')}}" class="col-xl-3 mb-xl-0 col-lg-6 mb-4 col-md-6 col-sm-6">
             <div class="widget-content-area  data-widgets br-4">
                 <div class="widget  t-sales-widget">
                     <div class="media">
                         <div class="icon ml-2">
                             <i class="flaticon-table"></i>
                         </div>
                         <div class="media-body text-right">
                             <p class="widget-text mb-0">Mock Test</p>
                             <!-- <p class="widget-numeric-value">24,017</p> -->
                         </div>
                     </div>
                     <!-- <p class="widget-total-stats mt-2">552 New Orders</p> -->
                 </div>
             </div>
         </a>
         <a href="{{route('user.quiz')}}" class="col-xl-3 col-lg-6 col-md-6 col-sm-6 mb-sm-0 mb-4">
             <div class="widget-content-area  data-widgets br-4">
                 <div class="widget  t-sales-widget">
                     <div class="media">
                         <div class="icon ml-2">
                             <i class="flaticon-copy"></i>
                         </div>
                         <div class="media-body text-right">
                             <p class="widget-text mb-0">Daily Quiz</p>
                             <!-- <p class="widget-numeric-value">92,251</p> -->
                         </div>
                     </div>
                     <!-- <p class="widget-total-stats mt-2">390 New Customers</p> -->
                 </div>
             </div>
         </a>
         <a href="{{route('user.course_material')}}" class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
             
             <div class="widget-content-area  data-widgets br-4">
                 <div class="widget  t-sales-widget">
                     <div class="media">
                         <div class="icon" style="max-width: 30%;">
                             <i class="flaticon-mail-19"></i>
                         </div>
                         <div class="media-body text-right">
                             <p class="widget-text mb-0">Course Material</p>
                             <!-- <p class="widget-numeric-value">9.5 M</p> -->
                         </div>
                     </div>
                     <!-- <p class="widget-total-stats mt-2">$2.1 M This Week</p> -->
                 </div>
             </div>
         </a>
      </div>
      <div class="row">
        <div class="col-lg-6 layout-spacing">
          <div class="statbox widget box box-shadow">
            <div class="widget-header">
              <div class="row">
                <div class="col-xl-12 col-md-12 col-sm-12 col-12 text-center mt-2">
                    <h2><b>Today's Test</b></h2><hr/>
                </div>           
              </div>
            </div>
            <div class="widget-content widget-content-area">
              <table class="table-striped">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Test</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                   @if(isset($student->test) && $student->test >0)
                    <tr class="tablerow">
                      <td>1</td>
                      <td class="user-email">Test {{$student->test}}</td>
                      <td class="user-mobile nav-item">
                        <form action = "{{route('user.start_mock_test')}}" method = "post" >
                          @csrf
                          <input type = 'hidden' name = 'type' value = 'test'           >
                          <input type = 'hidden' name = 'test' value = '{{$student->test}}'    >
                          <button type = 'submit' class = 'button-lnk nav-link formButton transparentformButton'>Start</button>
                        </form>

                        
                      </td>
                    </tr>
                  @else
                    <tr class="tablerow"><td colspan="3" class="text-center" >No Test Assigned for Today !!</td></tr>
                  @endif
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="col-lg-6 layout-spacing">
            <div class="statbox widget box box-shadow">
             <div class="widget-header">
               <div class="row">
                 <div class="col-xl-12 col-md-12 col-sm-12 col-12 text-center mt-2">
                     <h2><b>Today's Quizzes</b></h2><hr/>
                 </div>           
               </div>
             </div>
             <div class="widget-content widget-content-area">
               <table class="table-striped">
                 <thead>
                   <tr>
                     <th>#</th>
                     <th>Quiz</th>
                     <th>Action</th>
                   </tr>
                 </thead>
                 <tbody>
                   @if(isset($student->quiz1) && $student->quiz1 >0)
                     <tr class="tablerow">
                       <td>1</td>
                       <td class="user-email">Day {{$student->quiz1}}</td>
                       <td class="user-mobile nav-item">
                         <form action = "{{route('user.start_quiz')}}" method = "get" >
                          
                           <input type = 'hidden' name = 'type' value = 'quiz1'           >
                           <input type = 'hidden' name = 'quiz' value = '{{$student->quiz1}}'>
                           <!-- <input type = 'hidden' name = 'quiz_no'   value = 'quiz1'> -->
                           <button type = 'submit' class = 'button-lnk nav-link formButton transparentformButton'>Start</button>
                         </form>

                         
                       </td>
                     </tr>
                   @endif
                   @if(isset($student->quiz2) && $student->quiz2 >0)
                     <tr class="tablerow">
                       <td>2</td>
                       <td class="user-email">Day {{$student->quiz2}}</td>
                       <td class="user-mobile nav-item">
                         <form action = "{{route('user.start_quiz')}}" method = "get" >
                          
                           <input type = 'hidden' name = 'type' value = 'quiz2'>
                           <input type = 'hidden' name = 'quiz' value = '{{$student->quiz2}}'>
                           <!-- <input type = 'hidden' name = 'quiz_no'   value = 'quiz2'> -->
                           <button type = 'submit' class = 'button-lnk nav-link formButton transparentformButton'>Start</button>
                         </form>

                         
                       </td>
                     </tr>
                   @endif
                   @if(isset($student->quiz3) && $student->quiz3 >0)
                     <tr class="tablerow">
                       <td>3</td>
                       <td class="user-email">Day {{$student->quiz3}}</td>
                       <td class="user-mobile nav-item">
                         <form action = "{{route('user.start_quiz')}}" method = "get" >
                          
                           <input type = 'hidden' name = 'type' value = 'quiz3'           >
                           <input type = 'hidden' name = 'quiz' value = '{{$student->quiz3}}'    >
                           <!-- <input type = 'hidden' name = 'quiz_no'   value = 'quiz3'> -->
                           <button type = 'submit' class = 'button-lnk nav-link formButton transparentformButton'>Start</button>
                         </form>

                         
                       </td>
                     </tr>
                   @endif
                   @if((isset($student->quiz1) && $student->quiz1 =='0') && (isset($student->quiz2) && $student->quiz2 =='0') && (isset($student->quiz3) && $student->quiz3 =='0'))
                     <tr class="tablerow">
                        <td colspan="3" class="text-center" >No Quiz Assigned for Today !!</td></tr>
                   @endif 
                 </tbody>
               </table>
             </div>
           </div>
         </div>
      </div>
   </div>
</div>
@endsection('content')

resources/views/user/quiz-result.blade.php
@extends('layouts.user-app')
@section('content')
<style type="text/css">
   .content.quiz
   {
      padding: 0px !important;
   }
   .content.quiz .score
   {
      font-size: 25px;
      font-weight: bold;
      line-height: 35px;
   }
   .result .finish-quiz
   {
      display: inline-block;
      width: 200px;
      height: 51px;
      font-weight: bold;
   } 
   .result .finish-quiz a:hover {
    color: #fff;
    text-decoration: none;
   }
</style>
<link rel="stylesheet" type="text/css" href="{{ asset('css/omr.css') }}" />
<div class="row" id="cancel-row" >
  <div class="col-lg-12 layout-spacing">
    <img src="{{ asset('home/images/logo.png') }}" class = 'tnq_logo img-fluid ml-4'>
    <div class = 'result test' style="margin-top: 300px;">
        
      @if($score < 80)
         <img src="{{ asset('home/images/fail.PNG') }}">
         <div class = 'pf'> You did not pass the quiz. </div>
      @else
         <img src="{{ asset('home/images/pass.PNG') }}">
         <div class = 'pf'> Well done. You passed! </div>

      @endif
         <div class = 'content quiz'> Your score: 
            <span class = 'score'><?php echo '   '.$score; ?> </span>
         </div>
         <div class = 'content quiz'> Passing score: 
            <span class = 'score'>80 </span>
         </div>
      @if ($score >= 80)
         <div class = 'finish-quiz nav-link formButton'>
            <a href="{{route('user.quiz_review',['quiz'=>$quiz,'date'=>$date])}}" 
             class = 'cursor'> REVIEW QUIZ </a>
         </div>
      @endif

      <div class = 'finish-quiz nav-link formButton transparentformButton'>
         <a href="{{route('user.quiz')}}" class = 'cursor'> FINISH </a>
      </div>
    </div>
  </div>
</div>
@endsection('content')

resources/views/user/start-quiz.blade.php
@extends('layouts.user-app')
@section('content')

<div id="content" class="main-content">
  <div class="container">
    <div class="page-header">
       <!-- <div class="page-title">
          <h3>Lectures</h3>
       </div> -->
    </div>
    <div class="row mt-4" id="cancel-row">
      <div class="col-lg-12 layout-spacing">
        <div class="statbox widget box box-shadow">
          <div class="widget-header">
              <div class="row">
                  <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                    <h2><b>Quizzes</b></h2>
                   
                  </div>                      
              </div>
          </div>
          <div class="widget-content widget-content-area">
            <div class="row">
              <div class="col-lg-12">
                <section class="pricing-section bg-11">
                    <div class="pricing pricing--norbu">
                       <div class = 'start test'>
                         
                          
                          <div class = "table test">  
                            <div class = 'row'>
                              <div class = 'cell no col-md-12 text-center'> Day <?php echo $quiz;?> <a href = "{{route('user.quiz')}}" class = 'close'>X</a></div>
                            </div>
                            <div class = 'row'>
                              <div class = 'cell content'>If you click the button below, your quiz will begin. Start the quiz when you are ready.</div><br/>
                            </div>
                            <div class = 'row'>
                              <div class = 'cell warning'>Warning: Once you click the 'GET STARTED' button, your access to this quiz is no longer available! <br> Do not reload or leave the page after the quiz begins.</div>
                            </div>
                            <div class = 'row mt-4'>
                              <div class = 'cell button col-md-12 text-center'>
                                <a href="{{route('user.load_quiz_omr',['type'=>$type,'quiz'=>$quiz])}}" class ='button'> GET STARTED </a></div>
                            </div>
                          </div>
                        </div>
                    </div>
                </section> 
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection('content')